# Generated by Django 3.0.6 on 2020-06-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
