# Generated by Django 3.0.6 on 2020-06-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader_app', '0002_auto_20200604_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='grade_denominator',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='essay',
            name='grade_numerator',
            field=models.IntegerField(default=0),
        ),
    ]
