# Generated by Django 3.0.6 on 2020-06-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader_app', '0002_auto_20200601_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
