# Generated by Django 3.0.6 on 2020-06-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader_app', '0003_auto_20200601_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
