# Generated by Django 3.0.6 on 2020-06-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader_app', '0003_auto_20200601_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=150)),
                ('assignment_description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='assignments',
            field=models.ManyToManyField(to='grader_app.Assignment'),
        ),
    ]
