# Generated by Django 3.0.6 on 2020-06-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader_app', '0003_auto_20200601_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student',
            field=models.BooleanField(default=False),
        ),
    ]
