# Generated by Django 3.0.6 on 2020-06-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader_app', '0004_auto_20200602_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='marked_body',
            field=models.TextField(default=''),
        ),
    ]
